USE teamPrj1126;

CREATE TABLE faq
(
    id         INT AUTO_INCREMENT PRIMARY KEY,
    `question` VARCHAR(50)  NOT NULL,
    answer     VARCHAR(500) NOT NULL,
    writer     VARCHAR(20)  NOT NULL REFERENCES member (nickname),
    inserted   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE faq;